
services:
  apple_crypto:
    build: .
    container_name: apple_crypto_container
    depends_on:
      - apple_crypto_db
      - apple_crypto_redis
    ports:
      - 8080:8080
    environment:
    # this should be added even it is in application.yml
      db-url: jdbc:postgresql//apple_crypto_db:5433/apple_crypto
      db-username: jarvis
      db-password: ilnur@089
      SPRING_DATA_REDIS_HOST: apple_crypto_redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: apple_crypto_rabbit
    restart: always

  apple_crypto_db:
    image: postgres
    restart: always
    ports:
    # this port is busy by postgres on my pc that's why it's custom
      - 5433:5433
    environment:
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: ilnur@089
      POSTGRES_DB: apple_crypto
  
  apple_crypto_redis:
    image: redis:latest
    ports:
      - 6380:6379

  apple_crypto_rabbit:
    image: rabbitmq:3-management
    container_name: apple_crypto_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rab
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: vhost
    ports:
      - 5672:5672
      - 15672:15672
