spring:
    data:
        redis:
            host: localhost
            port: 6379
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        url: jdbc:postgresql://localhost:5432/apple_crypto
        username: jarvis
        password: ilnur@089
        initialize: false

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

security:
    jwt:
        secret-key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
        expiration-time: 3600000000000 

management:
    endpoints:
        web:
            exposure:
                include: "*"